### ISSUE TITLE
模板使用DIY的问题

### ISSUE THREAD

**Issue by wxin00** [branchzero/discuz-x32-php7#1]
使用DIY时 导入DIY文件完成后点击保存 无效 或者说有延迟 需要多导入保存几次才能生效 并有几率假死 
环境如下：
系统信息
Discuz! 程序版本    Discuz! X3.2 Release 20150609 查看最新版本 专业支持与服务 Discuz!专用主机
UCenter 客户端版本 UCenter 1.6.0 Release 20141101
服务器系统及 PHP  Linux / PHP v7.0.0
服务器软件 nginx/1.9.6
服务器 MySQL 版本  5.5.34-log
上传许可    20M
当前数据库尺寸   5.7 MB

**Comment by branchzero** [comment]
收到，等下测试下  
<br  
—  
BranchZero Sun  
A Multi-Stack Web Developer &amp;&amp; Operations Engineer  
@Hangzhou Liangjiang Network Technology Co., Ltd.  
Tel: +86.15355712337 (9:00 - 22:00)  
Email: branchzero@elemenx.com  
HP: http://www.elemenx.com/

**Comment by branchzero** [comment]
请提供一下你导入的diy的xml文件

**Comment by wxin00** [comment]
http://pan.baidu.com/s/1o7uQJ8m

**Comment by branchzero** [comment]
这边测试无问题，一次保存。
印象中之前也有用户的机器在非修改版的DZ上也碰到类似问题。
建议根据机器的实际情况，调整下 Nginx 与 PHP-FPM 的相关参数。

**Comment by branchzero** [comment]
比如
调整最大的POST大小（如果过小的话）
PHP的最长执行时间
等与该操作相关的操作

**Comment by xianwenyin** [comment]
```
怎么patch啊，不会使用啊 
```

**Comment by xianwenyin** [comment]
能否详细点如何patch

**Comment by Mushan3420** [comment]
你要patch哪里？

**Comment by xianwenyin** [comment]
就是这个文件x32_php7_patch.diff 已经下载下来了 如何使用。。

**Comment by branchzero** [comment]
@xianwenyin 不会用的话，切到dev分支下载，或者到release直接下载完整的源码。

**Comment by xianwenyin** [comment]
哦 好的
