### ISSUE TITLE
手机版报错 Function name must be a string

### ISSUE THREAD

**Issue by Mushan3420** [branchzero/discuz-x32-php7#2]
手机版报错 Function name must be a string
![113102akkgqqxkfwzcqqqq](https://cloud.githubusercontent.com/assets/5007900/11620010/6535b2f4-9ce9-11e5-9582-d850b74527b3.png)
网址（用手机访问） http://bbs.euyyue.com/forum.php?mobile=2
环境 CentOS 7 x64 AMH LAMP php-stable-1.0 （PHP 7.0）

**Comment by branchzero** [comment]
首先，插件不保证全部兼容，因为有一些写法到php7是不兼容的。。。
这次主要检查主程序的问题，外部插件不能一一解决，再碰到类似问题请依法如下方法一样炮制即可解决，不再单独解决了。
这个问题的话，到source/plugin/wechat/wechat.class.php的288行把

```
$return = $class->$hook['method']($type);
```

替换成

```
$return = call_user_func(array($class, $hook['method']), $type);
```
