### ISSUE TITLE
未登录时无法打开首页

### ISSUE THREAD

**Issue by Mushan3420** [branchzero/discuz-x32-php7#3]
未登录时无法打开首页，打开一片空白。必须先从后台登陆，才能显示首页。
网址（用手机访问） http://bbs.euyyue.com/
环境 CentOS 7 x64 AMH LAMP php-stable-1.0 （PHP 7.0）

**Comment by branchzero** [comment]
重复提问 #2

**Comment by branchzero** [comment]
重复提问 #2
