### ISSUE TITLE
伪静态问题

### ISSUE THREAD

**Issue by Mushan3420** [branchzero/discuz-x32-php7#4]
开启伪静态后，页面空白，经排查，伪静态规则正常，推测DZ文件内容有错。
目前在努力排查中。

**Comment by Mushan3420** [comment]
环境 Linux Apache

**Comment by branchzero** [comment]
是基于V0.1.1搭建的么？
能开启PHP默认的错误信息回报么？
开启之后在config_global.php加一个$_config['debug'] = 2;看看错误信息

**Comment by Mushan3420** [comment]
是基于最新版搭建的，你说我重复提问，我排查了一天，竟然是伪静态问题。。。我去开错误日志。。。

**Comment by Mushan3420** [comment]
错误报告开了，配置也加了，但日志看不到。。。醉了。。。AMH5.2

**Comment by branchzero** [comment]
php.ini中
display_error确保on
error_report确保-1

**Comment by Mushan3420** [comment]
error_reporting = E_ALL &~E_NOTICE
display_errors = On
display_startup_errors = On
log_errors = On
log_errors_max_len = 2048
ignore_repeated_errors = On
ignore_repeated_source = On
report_memleaks = On
track_errors = On
html_errors = On
error_log = /home/wwwroot/lamp-stable/logs/amh-php-errors.log

**Comment by Mushan3420** [comment]
http://bbs.euyyue.com/
你访问下，我看看日志能不能有。

**Comment by branchzero** [comment]
return 200，有尾部，大概是缓存了不正确的页面，去后台更新下缓存吧。
然后再访问一次看看会不会报什么错误

**Comment by Mushan3420** [comment]
更新无数次了，只有关掉伪静态才行。

**Comment by branchzero** [comment]
你是什么时候下的包来部署的，昨天晚上我记得我做了一次修正，如果不是0.1.1的话请手动更新下最后一次提交改的两个文件

**Comment by Mushan3420** [comment]
我就是0.1.1，真的。

**Comment by branchzero** [comment]
我也试试看好了

**Comment by Mushan3420** [comment]
建议用全量文件形式放上去吧，大家一起更新，改了什么标注出来。这个diff不方便。

**Comment by Mushan3420** [comment]
还有就是UCenter空白，你发现没？

**Comment by branchzero** [comment]
@Mushan3420 法务问题，不敢公然侵权，我再另外开一个dev支更新好了。
复现出空白界面了，等下我再研究下。。。

**Comment by Mushan3420** [comment]
http://bbs.euyyue.com/uc_server/

**Comment by Mushan3420** [comment]
没有法务问题吧。。。开源软件，二次开发，并非商用。

**Comment by Mushan3420** [comment]
另外，自带的手机版和微社区，中午修复的问题：
/source/plugin/wechat/wechat.class.php
288行
$return = call_user_func(array($class, $hook['method']), $type);

/source/plugin/mobile/mobile.class.php
280行
call_user_func(array($pluginclasses[$hook['class']], $hook['method']),$param);

更新的时候同步上去吧。

其实全量放上去是最好的办法。

**Comment by branchzero** [comment]
dev分支放全量，就这样。
刚才那个伪静态问题解决了，等下同步上去

**Comment by Mushan3420** [comment]
哇，这么快，求方法。。。太令人震惊了！
还有UCenter空白的问题，这是我今天发现的最后一个问题。

**Comment by branchzero** [comment]
@Mushan3420 空白的问题我先看看吧，解决完一块push

**Comment by Mushan3420** [comment]
请求。。。先把伪静态解决掉。。。

**Comment by branchzero** [comment]
@Mushan3420 两个都搞定了，稍等会儿我推上去

**Comment by Mushan3420** [comment]
我已经彻底被你折服了。。。效率好高。。。求代码。。。看看这个错误到底是什么鬼。。。

**Comment by branchzero** [comment]
@Mushan3420 切到Dev支更新，或者直接去下最新的release https://github.com/branchzero/discuz-x32-php7/tree/dev

**Comment by branchzero** [comment]
问题已解决

**Comment by Mushan3420** [comment]
## 另外，还有几个官方遗留的BUG，被不小心同步上去了，如果方便的话，dev 开了，给我个权限，我同步上去，或者你同步上去。详情如下：

当在后台设置论坛QQ在线客服号码，或者在个人信息联系方式里填写QQ号码后，点击页面右下角的QQ在线图标或点击帖子左侧个人信息下的发起QQ聊天，弹出的窗口中都显示“抱歉，无法发起临时会话，您可以添加对方为好友以发送消息”

对比代码发现，出错的原因是：代码里的是大写，而能正常发起会话的首写字母都是小写。

右下角：修改template\default\common\footer.htm(这是默认模版，非默认模版修改修改template\你的模版\common\footer.htm)

查找msgrd，在第60行

将Uin的大写改成小写uin;

贴内个人信息：source\module\forum\forum_viewthread.php

搜索msgrd，在第1348行

将Uin的大写改成小写uin。

迷你资料卡：template\default\forum\viewthread_node.htm

搜索msgrd，在第47行

将Uin的大写改成小写uin。

个人空间个人资料页：source\function\function_profile.php

搜索msgrd，在第329行

将Uin的大写改成小写uin。

贴内插入QQ：在后台  界面   编辑器设置   Discuz！代码  点qq后面的详情  

在替换内容:下的编辑框，<a href="http://wpa.qq.com/msgrd?V=3&Uin={1}&Site=[Discuz!]&from=discuz&Menu=yes" target="_blank"><img src="static/image/common/qq_big.gif" border="0"></a>

## 将Uin改成uin。

Discuz X2.5/X3版本中，如果你在“后台->全局->SEO设置”的任意标题中添加类似“ - ”含有空格的字符，Discuz会自动略掉导致该空格丢失，经过研究，得出以下解决方法：

打开/source/class/helper/helper_seo.php，在49行附近找到如下代码：

public static function strreplace_strip_split($searchs, $replaces, $str) {
    $searchspace = array('((\s_-\s_)+)', '((\s_\,\s_)+)', '((\s_|\s_)+)', '((\s_\t\s_)+)', '((\s__\s_)+)');
    $replacespace = array('-', ',', '|', ' ', '_');
    return trim(preg_replace($searchspace, $replacespace, str_replace($searchs, $replaces, $str)), ' ,-|_');
}

将以上代码改为

public static function strreplace_strip_split($searchs, $replaces, $str) {
    $searchspace = array('(((\s)_-(\s)_)+)', '(((\s)_\,(\s)_)+)', '(((\s)_|(\s)_)+)', '(((\s)_\t(\s)_)+)', '(((\s)__(\s)_)+)');
    $replacespace = array('$3-$3', '$3,$3', '$3|$3', '$3 $3', '$3_$3');
    return trim(preg_replace($searchspace, $replacespace, str_replace($searchs, $replaces, $str)), ' ,-|_');

## }

还有swf无法播放的问题，替换/static/image/common/ 下面两个swf 

---

**Comment by branchzero** [comment]
好的，收到，等会儿更新上去

**Comment by branchzero** [comment]
@Mushan3420 贴的代码貌似有些问题，算了，把你拉到maintainer里面，你来修改提交吧，多谢了。

**Comment by Mushan3420** [comment]
嗯嗯，不然我每次覆盖完了，还要重做BUG修复。

**Comment by branchzero** [comment]
@Mushan3420 权限丢你了，你来动手了，我先去休息了，晚安：）
