### ISSUE TITLE
Official Has Updated 20151208, DO NOT UPGRADE DIRECTLY!

### ISSUE THREAD

**Issue by branchzero** [branchzero/discuz-x32-php7#5]
Please Wait patiently to let me merge the patch!

**Comment by Mushan3420** [comment]
已醉，官方遇到安全漏洞，反应倒是挺快的，就是不修复BUG

**Comment by branchzero** [comment]
@Mushan3420 嘛，习惯了，接触 DZ 六七年了，感觉被腾讯收了之后就是这种态度了。。。

**Comment by Mushan3420** [comment]
真是呵呵哒，只要没有安全漏洞，其他不管。不过据说开发团队否解散了，也只能这样了吧……

**Comment by branchzero** [comment]
@Mushan3420 对，据我了解，就剩猴子了。。。其他都转去 云平台 或者 腾讯云 了。

**Comment by Mushan3420** [comment]
洋葱是戴志康的新项目？这东西挺有潜力呀，中国版的谷歌验证码。

**Comment by branchzero** [comment]
@Mushan3420 其实没有太大的盈利潜力啊，毕竟替代品太多了。。。

**Comment by Mushan3420** [comment]
大神有没有一点时间，帮我看一个插件的兼容性问题，我黔驴技穷了。。。

**Comment by branchzero** [comment]
@Mushan3420 插件标识符，还有对应的应用中心的地址

**Comment by Mushan3420** [comment]
插件标识符 bigapp
应用中心地址 http://addon.discuz.com/?@bigapp.plugin
问题描述 http://bigapp.youzu.com/bbs/forum.php?mod=viewthread&tid=516
插件官方回复 暂未测试。。。我无语了。。。

**Comment by branchzero** [comment]
@Mushan3420 没办法直接下，装完的插件路径source/plugin/bigapp打包丢网盘放链接吧

**Comment by Mushan3420** [comment]
我先拉下来，看看能不能学你，开个源。。。其实我没用过这个GitHub，为跟你一起更新，昨晚现学的。。。

**Comment by Mushan3420** [comment]
大神你好~~~权限给你了，现跟你学的。

**Comment by Mushan3420** [comment]
文件在 GitHub 上了，麻烦大神给看下。
