### ISSUE TITLE
在风格管理中-模版管理有错误

### ISSUE THREAD

**Issue by zoapk** [branchzero/discuz-x32-php7#6]
Discuz! System Error
Call to a member function read() on boolean

PHP Debug
No. File    Line    Code
1   admin.php   57  require()
2   source/admincp/admincp_styles.php   139 break()

**Comment by branchzero** [comment]
测试没有问题，无法复现，请问下你是在什么情况下触发这个问题的。

**Comment by branchzero** [comment]
定位source/admincp/admincp_styles.php的139行，把

```
while($searchentry = $searchdir->read()) {
```

改成

```
while(($searchentry = $searchdir->read()) !== false) {
```

然后再试，如果遇到类似问题请依葫芦画瓢，但是这个问题很可能是你进行了某些操作之后导致目录文件结构不完整造成的，我在默认情况下无法复现这个问题。

**Comment by Mushan3420** [comment]
此问题是否算BUG呢，确认了才能同步到dev - -

**Comment by branchzero** [comment]
@Mushan3420 本地默认条件下测试没问题的我倾向于不动，很可能是他的文件结构是缺的。

**Comment by zoapk** [comment]
默认没问题，我安装其他风格时候就会这样10配色小米完美版 utf8

**Comment by branchzero** [comment]
@zoapk 晚点我再测试吧，issue先留着，有空再说。

**Comment by branchzero** [comment]
给客户尝试开发了一套模板，也是在本地PHP7环境进行测试，并没有复现这个问题，可能是模板本身存在一些不能兼容的地方吧，建议你换别的模板试试？
