### ISSUE TITLE
CRLF变成了LF

### ISSUE THREAD

**Issue by chrysanthemum** [branchzero/discuz-x32-php7#7]
CRLF变成了LF，有点不适应了

**Comment by Mushan3420** [comment]
没看明白

**Comment by chrysanthemum** [comment]
哦 是discuz默认CRLF换行，这个源码变成了LF换行了

**Comment by chrysanthemum** [comment]
这个项目很好，说不定可以吸引很多人加入，现在官方基本是死了

**Comment by chrysanthemum** [comment]
个人提个想法：）希望项目的目的不光是让discuz可以运行在php7上，而且可以运行在生产环境，可以慢慢来

**Comment by branchzero** [comment]
额，这应该是提交的时候 Git 里面设定的自动转换，只要你不用记事本编辑代码就不会受到影响吧。。。。
然后，运不运行在生产环境取决于你，但是出了问题你得自行解决，我不负任何责任。

**Comment by branchzero** [comment]
额，这应该是提交的时候 Git 里面设定的自动转换，只要你不用记事本编辑代码就不会受到影响吧。。。。
然后，运不运行在生产环境取决于你，但是出了问题你得自行解决，我不负任何责任。额，这应该是提交的时候 Git 里面设定的自动转换，只要你不用记事本编辑代码就不会受到影响吧。。。。
然后，运不运行在生产环境取决于你，但是出了问题你得自行解决，我不负任何责任。
