### ISSUE TITLE
支付宝接口不可用，会提示ILLEGAL_PARTNER_EXTERFACE

### ISSUE THREAD

**Issue by musnow** [branchzero/discuz-x32-php7#8]
接口问题希望可以帮忙修复一下呢，
还有现在官方居然更新了版本，新版本号20151208
不知道可以不可以跟进一下呢，谢谢大大了~

**Comment by Mushan3420** [comment]
你看dev分支，都已经更新了，也解决了。

**Comment by musnow** [comment]
昂，我刚刚下载的文件，然后再本地测试，然而并没有
我这边用的双接口v3，你们不是改了接口吧=。=
我用的官方最新的版本没有出现这个问题

**Comment by Mushan3420** [comment]
官方版本原先在双接口下没事，但现在支付宝已经停止申请双接口了。个人用户请申请担保交易，企业用户请申请即时到帐。
原来遗留的双接口暂未到期用户，如有问题，可以自己改回去。申请新接口后，记得改回来。
参见 http://toplife.discuz.net/thread-3697197-1-1.html

**Comment by musnow** [comment]
好的，接口可以使用了，感谢解答，
还有个问题，能不能帮忙看看呢

在后台设置风格，界面基础图片目录的时候，如果使用了https就会在前台自动加域名上去导致url不可用，貌似官方也是有这个问题的，不知道这个文件在哪里改呢

![qq 20160102155216](https://cloud.githubusercontent.com/assets/10286849/12073740/3ba4b3a6-b169-11e5-93da-579811ea87e1.png)
![qq 20160102155239](https://cloud.githubusercontent.com/assets/10286849/12073741/3bac391e-b169-11e5-885b-9845c55e5f3b.png)

**Comment by Mushan3420** [comment]
Discuz 不能识别https链接，就连云平台都强制要求http，暂时别折腾了。

**Comment by musnow** [comment]
昂，这个也是==
云平台也没什么用，暂时不用了，
这边我直接改主题吧，不用也是可以的==
很是心累
感谢大大回答~

**Comment by branchzero** [comment]
IMGDIR最好还是用相对路径吧，因为DZ有些调用图片的地方用的是{$_G[siteurl]}{IMGDIR}（不太规范），你要把这些都改过来略不容易啊。

**Comment by branchzero** [comment]
@musnow 还好，试了下，总共 9 个文件 36 处 match，改改还是可以解决这个问题的。

**Comment by branchzero** [comment]
@musnow 无视我说的，只用改template/default/common/header.htm这么一个文件的4-7行就好了，其他都是给人定制东西重复引用的。

**Comment by musnow** [comment]
@branchzero 这个文件4~7只是页面favicon的路径吧=,=
看了半天怎么感觉不对呢， 看了一下生成的文件，果然只是页头==
